CREATE DATABASE music;

CREATE TABLE tracks (
    id int,
    artist VARCHAR(255),
    name VARCHAR(255),
    genre VARCHAR(255),
    year VARCHAR(4)
);


INSERT INTO `tracks` (`id`, `artist`, `name`, `genre`, `year`) VALUES
(1, 'Dr. Richard Hill I', 'Error veritatis quibusdam.', 'Pop', '1973'),
(2, 'Alford Botsford', 'Magni non sit.', 'Country', '1981'),
(3, 'Dr. Brant Rowe Sr.', 'Ipsam id.', 'Country', '1986'),
(4, 'Dr. Gaston Kling', 'Labore quos.', 'Jazz', '1977'),
(5, 'Amely Crist', 'Error minus.', 'Soul', '2013'),
(6, 'Isadore Howe Sr.', 'Dolores recusandae.', 'Country', '2021'),
(7, 'Aiden Dickens', 'Expedita quo.', 'Jazz', '1983'),
(8, 'Prof. Merle Kerluke', 'Non qui ducimus.', 'Pop', '1975'),
(9, 'Leonie Dickens', 'Officiis corrupti dicta.', 'Soul', '2004'),
(10, 'Isom Boyle', 'Assumenda maiores.', 'Country', '1984'),
(11, 'Emmanuelle Ledner', 'Tempora error.', 'Jazz', '1987'),
(12, 'Destinee Ullrich', 'Atque cum.', 'Jazz', '1989'),
(13, 'Anastasia Nader', 'Provident itaque.', 'Country', '1990'),
(14, 'Ole Schulist', 'Cum soluta.', 'Soul', '1981'),
(15, 'Mr. Harry Kuphal', 'Enim unde molestiae.', 'Country', '1972'),
(16, 'Dr. Sheridan Treutel Jr.', 'Maxime corporis incidunt.', 'Pop', '1999'),
(17, 'Mrs. Evangeline Kris Jr.', 'Rem consequatur sed.', 'Disco', '1988'),
(18, 'Marley Weissnat DVM', 'Quo doloribus.', 'Pop', '1984'),
(19, 'Gretchen Mills DVM', 'Fugit modi.', 'Disco', '1991'),
(20, 'Tod Purdy', 'Impedit neque et.', 'Funk', '2015'),
(21, 'Oda Purdy II', 'Deleniti sunt.', 'Disco', '1993'),
(22, 'Prof. Gina Rodriguez', 'Inventore voluptatem.', 'Pop', '1987'),
(23, 'Dr. Felicita Barton PhD', 'Adipisci dolorem.', 'Country', '2000'),
(24, 'Mr. Ari Koelpin I', 'Neque ea.', 'Pop', '1993'),
(25, 'Lera Wintheiser', 'Corporis molestias labore.', 'Funk', '2011'),
(26, 'Maia Crooks', 'Quod cumque.', 'Disco', '1991'),
(27, 'Dr. Eula Gleason I', 'Velit quam.', 'Jazz', '1977'),
(28, 'Marcel Wolf', 'Ipsam et nisi.', 'Country', '2002'),
(29, 'Jerad Strosin', 'Dolorem autem.', 'Country', '1989'),
(30, 'Marcel Jacobson', 'Nobis repudiandae earum.', 'Country', '2008'),
(31, 'Johnson Gutmann', 'Consectetur dolores sequi.', 'Jazz', '1981'),
(32, 'Diego Shanahan', 'Consequuntur maiores sed.', 'Soul', '2008'),
(33, 'Tremaine Schroeder', 'Similique animi.', 'Country', '2000'),
(34, 'Sam Brakus', 'Sunt beatae est.', 'Jazz', '1993'),
(35, 'Monroe Becker', 'Iusto aut.', 'Jazz', '2000'),
(36, 'Stephany Grimes', 'Dolor et molestiae.', 'Pop', '1983'),
(37, 'Franz Kub', 'Ad earum error.', 'Soul', '2017'),
(38, 'Hubert Goodwin', 'Suscipit rem.', 'Pop', '2004'),
(39, 'Adah Walker', 'Omnis eos et.', 'Disco', '1972'),
(40, 'Dr. Michelle Bayer Sr.', 'Atque qui error.', 'Rock', '2018'),
(41, 'Dr. Damian Kertzmann', 'Magni sed.', 'Country', '1989'),
(42, 'Dr. Fausto Dooley DDS', 'Provident natus et.', 'Jazz', '2012'),
(43, 'Ms. Amira Borer Jr.', 'Architecto laborum.', 'Soul', '1991'),
(44, 'Prof. Nelson Champlin', 'Id sed non.', 'Country', '2010'),
(45, 'Houston Roob', 'Dolores aspernatur nemo.', 'Jazz', '2009'),
(46, 'Ms. Shania O\'Keefe', 'Corporis aut vitae.', 'Jazz', '1989'),
(47, 'Mrs. Amely Hand Jr.', 'Molestias expedita vel.', 'Pop', '1998'),
(48, 'Sven Dietrich', 'Nihil ut.', 'Pop', '2018'),
(49, 'Dominique Kunde', 'Voluptas ut enim.', 'Funk', '1989'),
(50, 'Dora Gutmann', 'Nobis error.', 'Jazz', '2008'),
(51, 'Camden Langosh', 'Animi et.', 'Country', '2015'),
(52, 'Annetta Kilback', 'Quis provident quia.', 'Jazz', '2009'),
(53, 'Edmond Ullrich', 'Quia est iste.', 'Pop', '1971'),
(54, 'Dr. Elias Abernathy MD', 'Nisi facere laborum.', 'Pop', '1974'),
(55, 'Sheldon Lowe', 'Et aut sed.', 'Soul', '2002'),
(56, 'Dr. Domingo Baumbach', 'Nemo quidem repellat.', 'Jazz', '2001'),
(57, 'Prof. Ara Heathcote', 'Hic omnis iste.', 'Rock', '2019'),
(58, 'Barney Ernser', 'Minima suscipit nihil.', 'Rock', '2018'),
(59, 'Eloise Padberg', 'Occaecati ratione.', 'Jazz', '1999'),
(60, 'Manuela D\'Amore', 'Odit et quisquam.', 'Rock', '1990'),
(61, 'Russell Moore', 'Quaerat dolorem sit.', 'Soul', '1976'),
(62, 'Mr. Kennedi Ferry MD', 'Facilis officiis ratione.', 'Rock', '1971'),
(63, 'Connie Wolff', 'Vero distinctio perspiciatis.', 'Soul', '1978'),
(64, 'Makayla Langosh', 'Voluptas reprehenderit.', 'Funk', '2013'),
(65, 'Marjory Ledner III', 'Voluptatem sit.', 'Jazz', '1973'),
(66, 'Linda Homenick I', 'Adipisci rerum.', 'Jazz', '2009'),
(67, 'Amir Stanton', 'Voluptas quisquam.', 'Country', '1999'),
(68, 'Camron Botsford DDS', 'Officiis laudantium dignissimos.', 'Jazz', '1978'),
(69, 'Ottis Barton', 'Minima odit et.', 'Disco', '1975'),
(70, 'Mr. Nestor Hudson MD', 'Rem facere sed.', 'Pop', '2008'),
(71, 'Dr. Madisen Huels DDS', 'Qui consequatur ut.', 'Jazz', '2018'),
(72, 'Dr. Shawn Rosenbaum PhD', 'Voluptas inventore quisquam.', 'Country', '2011'),
(73, 'Herminio Rice', 'Non est.', 'Disco', '2015'),
(74, 'Ms. Destany Daniel V', 'Eveniet aspernatur.', 'Disco', '1987'),
(75, 'Delphia McGlynn IV', 'Ea ex.', 'Pop', '1999'),
(76, 'Nedra Howell', 'Amet sunt.', 'Funk', '1985'),
(77, 'Berry Feeney I', 'Exercitationem nam.', 'Jazz', '1983'),
(78, 'Mr. Garland Jenkins', 'Mollitia quia mollitia.', 'Rock', '1971'),
(79, 'Kylee Pacocha', 'Itaque asperiores modi.', 'Funk', '1978'),
(80, 'Rick Roberts IV', 'Impedit quo et.', 'Pop', '1972'),
(81, 'Francis Barton', 'Assumenda nesciunt.', 'Disco', '1993'),
(82, 'Prof. Hertha Powlowski MD', 'Placeat aliquid suscipit.', 'Soul', '1999'),
(83, 'Prof. Wyman Stokes DDS', 'Amet voluptas ab.', 'Disco', '1978'),
(84, 'Keeley Torp', 'Deleniti omnis.', 'Country', '2001'),
(85, 'Prof. Coty King IV', 'Qui tempore.', 'Pop', '2017'),
(86, 'Vicente Kerluke', 'Nemo aperiam.', 'Pop', '1980'),
(87, 'Prof. Kelli Rohan', 'Ducimus nesciunt.', 'Disco', '1975'),
(88, 'Mrs. Golda Schneider', 'Dolorem accusantium.', 'Disco', '1970'),
(89, 'Stan Doyle', 'In recusandae ut.', 'Jazz', '1999'),
(90, 'Wendell Cassin', 'Eaque beatae.', 'Country', '2000'),
(91, 'Myra Hettinger', 'Ab enim commodi.', 'Country', '1985'),
(92, 'Molly Bednar', 'Ut est aut.', 'Country', '2003'),
(93, 'Catharine Grimes', 'In accusamus molestias.', 'Rock', '2001'),
(94, 'Mrs. Sandra Ferry III', 'Velit repellat dolor.', 'Disco', '2003'),
(95, 'Elyssa Jakubowski', 'Quisquam ut.', 'Funk', '2012'),
(96, 'Miss Alexandra Mills', 'Rerum voluptas eum.', 'Country', '2018'),
(97, 'Casey Rempel', 'Qui nemo ad.', 'Disco', '1988'),
(98, 'Flossie Hand', 'Fugiat commodi.', 'Jazz', '2000'),
(99, 'Michaela Spinka', 'Optio perspiciatis.', 'Disco', '1971'),
(100, 'Reese Ziemann', 'Ipsum tempore est.', 'Disco', '2009');